//
// Generated by jfm-ios on 9/22/2018.
// Just Fast Model!!!
// Copyright © 2018 E7du. All rights reserved.
//

#import <jfm/jfm.h>

extern const NSString *MATCHINFO_MATCHID;

extern const NSString *MATCHINFO_USERID;

extern const NSString *MATCHINFO_HOMECOLOR;

extern const NSString *MATCHINFO_HOMESCORE;

extern const NSString *MATCHINFO_GUESTCOLOR;

extern const NSString *MATCHINFO_GUESTSCORE;

extern const NSString *MATCHINFO_STATUS;

extern const NSString *MATCHINFO_STAGE;

extern const NSString *MATCHINFO_MIN;

extern const NSString *MATCHINFO_SEC;

extern const NSString *MATCHINFO_HOMEPAUSECOUNT;

extern const NSString *MATCHINFO_GUESTPAUSECOUNT;

extern const NSString *MATCHINFO_HOMEFOULCOUNT;

extern const NSString *MATCHINFO_GUESTFOULCOUNT;

extern const NSString *MATCHINFO_BHOMEBALLCTRL;

extern const NSString *MATCHINFO_NOID;

extern const NSString *MATCHINFO_TABLE;

@interface MatchInfo : Model

@property (nonatomic, copy) NSString *matchid;

@property (nonatomic, copy) NSString *userid;

@property (nonatomic, copy) NSString *homecolor;

@property (nonatomic, assign) NSInteger homescore;

@property (nonatomic, copy) NSString *guestcolor;

@property (nonatomic, assign) NSInteger guestscore;

@property (nonatomic, assign) NSInteger status;

@property (nonatomic, assign) NSInteger stage;

@property (nonatomic, assign) NSInteger min;

@property (nonatomic, assign) NSInteger sec;

@property (nonatomic, assign) NSInteger homepausecount;

@property (nonatomic, assign) NSInteger guestpausecount;

@property (nonatomic, assign) NSInteger homefoulcount;

@property (nonatomic, assign) NSInteger guestfoulcount;

@property (nonatomic, assign) NSInteger bhomeballctrl;

@property (nonatomic, assign) NSUInteger noid;

@end

