//
// Generated by jfm-ios on 9/22/2018.
// Just Fast Model!!!
// Copyright © 2018 E7du. All rights reserved.
//

#import "MatchInfo.h"

NSString *MATCHINFO_MATCHID = @"matchid";

NSString *MATCHINFO_USERID = @"userid";

NSString *MATCHINFO_HOMECOLOR = @"homecolor";

NSString *MATCHINFO_HOMESCORE = @"homescore";

NSString *MATCHINFO_GUESTCOLOR = @"guestcolor";

NSString *MATCHINFO_GUESTSCORE = @"guestscore";

NSString *MATCHINFO_STATUS = @"status";

NSString *MATCHINFO_STAGE = @"stage";

NSString *MATCHINFO_MIN = @"min";

NSString *MATCHINFO_SEC = @"sec";

NSString *MATCHINFO_HOMEPAUSECOUNT = @"homepausecount";

NSString *MATCHINFO_GUESTPAUSECOUNT = @"guestpausecount";

NSString *MATCHINFO_HOMEFOULCOUNT = @"homefoulcount";

NSString *MATCHINFO_GUESTFOULCOUNT = @"guestfoulcount";

NSString *MATCHINFO_BHOMEBALLCTRL = @"bhomeballctrl";

NSString *MATCHINFO_NOID = @"noid";

NSString *MATCHINFO_TABLE = @"matchinfo_1";

@interface MatchInfo()
{
	NSString * _matchid;
	NSString * _userid;
	NSString * _homecolor;
	NSInteger _homescore;
	NSString * _guestcolor;
	NSInteger _guestscore;
	NSInteger _status;
	NSInteger _stage;
	NSInteger _min;
	NSInteger _sec;
	NSInteger _homepausecount;
	NSInteger _guestpausecount;
	NSInteger _homefoulcount;
	NSInteger _guestfoulcount;
	NSInteger _bhomeballctrl;
	NSUInteger _noid;
}
@end

@implementation MatchInfo

- (void)setMatchid:(NSString *)matchid
{
	[self set:@"matchid" value:matchid];
	_matchid = matchid;
}

- (NSString *)matchid
{
	return [self get:@"matchid" defaultValue:@"\"\""];
}

- (void)setUserid:(NSString *)userid
{
	[self set:@"userid" value:userid];
	_userid = userid;
}

- (NSString *)userid
{
	return [self get:@"userid" defaultValue:@"\"\""];
}

- (void)setHomecolor:(NSString *)homecolor
{
	[self set:@"homecolor" value:homecolor];
	_homecolor = homecolor;
}

- (NSString *)homecolor
{
	return [self get:@"homecolor" defaultValue:@"\"\""];
}

- (void)setHomescore:(NSInteger)homescore
{
	[self set:@"homescore" value:[NSNumber numberWithInteger:homescore]];
	_homescore = homescore;
}

- (NSInteger)homescore
{
	return [[self get:@"homescore" defaultValue:@0] integerValue];
}

- (void)setGuestcolor:(NSString *)guestcolor
{
	[self set:@"guestcolor" value:guestcolor];
	_guestcolor = guestcolor;
}

- (NSString *)guestcolor
{
	return [self get:@"guestcolor" defaultValue:@"\"\""];
}

- (void)setGuestscore:(NSInteger)guestscore
{
	[self set:@"guestscore" value:[NSNumber numberWithInteger:guestscore]];
	_guestscore = guestscore;
}

- (NSInteger)guestscore
{
	return [[self get:@"guestscore" defaultValue:@0] integerValue];
}

- (void)setStatus:(NSInteger)status
{
	[self set:@"status" value:[NSNumber numberWithInteger:status]];
	_status = status;
}

- (NSInteger)status
{
	return [[self get:@"status" defaultValue:@0] integerValue];
}

- (void)setStage:(NSInteger)stage
{
	[self set:@"stage" value:[NSNumber numberWithInteger:stage]];
	_stage = stage;
}

- (NSInteger)stage
{
	return [[self get:@"stage" defaultValue:@0] integerValue];
}

- (void)setMin:(NSInteger)min
{
	[self set:@"min" value:[NSNumber numberWithInteger:min]];
	_min = min;
}

- (NSInteger)min
{
	return [[self get:@"min" defaultValue:@0] integerValue];
}

- (void)setSec:(NSInteger)sec
{
	[self set:@"sec" value:[NSNumber numberWithInteger:sec]];
	_sec = sec;
}

- (NSInteger)sec
{
	return [[self get:@"sec" defaultValue:@0] integerValue];
}

- (void)setHomepausecount:(NSInteger)homepausecount
{
	[self set:@"homepausecount" value:[NSNumber numberWithInteger:homepausecount]];
	_homepausecount = homepausecount;
}

- (NSInteger)homepausecount
{
	return [[self get:@"homepausecount" defaultValue:@0] integerValue];
}

- (void)setGuestpausecount:(NSInteger)guestpausecount
{
	[self set:@"guestpausecount" value:[NSNumber numberWithInteger:guestpausecount]];
	_guestpausecount = guestpausecount;
}

- (NSInteger)guestpausecount
{
	return [[self get:@"guestpausecount" defaultValue:@0] integerValue];
}

- (void)setHomefoulcount:(NSInteger)homefoulcount
{
	[self set:@"homefoulcount" value:[NSNumber numberWithInteger:homefoulcount]];
	_homefoulcount = homefoulcount;
}

- (NSInteger)homefoulcount
{
	return [[self get:@"homefoulcount" defaultValue:@0] integerValue];
}

- (void)setGuestfoulcount:(NSInteger)guestfoulcount
{
	[self set:@"guestfoulcount" value:[NSNumber numberWithInteger:guestfoulcount]];
	_guestfoulcount = guestfoulcount;
}

- (NSInteger)guestfoulcount
{
	return [[self get:@"guestfoulcount" defaultValue:@0] integerValue];
}

- (void)setBhomeballctrl:(NSInteger)bhomeballctrl
{
	[self set:@"bhomeballctrl" value:[NSNumber numberWithInteger:bhomeballctrl]];
	_bhomeballctrl = bhomeballctrl;
}

- (NSInteger)bhomeballctrl
{
	return [[self get:@"bhomeballctrl" defaultValue:@0] integerValue];
}

- (void)setNoid:(NSUInteger)noid
{
	[self set:@"noid" value:[NSNumber numberWithUnsignedInteger:noid]];
	_noid = noid;
}

- (NSUInteger)noid
{
	return [[self get:@"noid" defaultValue:@(0)] unsignedIntegerValue];
}

+ (NSString *)primaryKey
{
	return @"noid";
}

+ (const NSString *)tableName
{
	return MATCHINFO_TABLE;
}

+ (const NSUInteger)v
{
	return 1;
}

+ (const NSString *)stmt
{
	return @"CREATE TABLE \"MatchInfo_1\" (\"matchid\" TEXT NOT NULL DEFAULT \"\",\"userid\" TEXT NOT NULL DEFAULT \"\",\"homecolor\" TEXT NOT NULL DEFAULT \"\",\"homescore\" INTEGER NOT NULL DEFAULT 0,\"guestcolor\" TEXT NOT NULL DEFAULT \"\",\"guestscore\" INTEGER NOT NULL DEFAULT 0,\"status\" INTEGER NOT NULL DEFAULT 0,\"stage\" INTEGER NOT NULL DEFAULT 0,\"min\" INTEGER NOT NULL DEFAULT 0,\"sec\" INTEGER NOT NULL DEFAULT 0,\"homepausecount\" INTEGER NOT NULL DEFAULT 0,\"guestpausecount\" INTEGER NOT NULL DEFAULT 0,\"homefoulcount\" INTEGER NOT NULL DEFAULT 0,\"guestfoulcount\" INTEGER NOT NULL DEFAULT 0,\"bhomeballctrl\" INTEGER NOT NULL DEFAULT 0,\"noid\" INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(\"noid\" AUTOINCREMENT))";
}

@end

